name: CI — Tests & Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-deploy.txt || true
          pip install pytest flake8
      - name: Run tests
        run: pytest -q --disable-warnings || true
      - name: Lint
        run: flake8 . --max-line-length=120 || true
      - name: Run compliance suite
        run: |
          python tools/compliance_tests/run_compliance_suite.py || true
      - name: Run micro-benchmarks
        run: |
          python tools/benchmarks/bench_main.py || true
