name: Deploy to Cloud
on:
  push:
    tags:
      - "v*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        run: |
          docker build -t crajkumarsingh/billgenerator:${GITHUB_REF_NAME} .
          docker push crajkumarsingh/billgenerator:${GITHUB_REF_NAME}